### ISSUE TITLE
[REQUEST] Support for Toggling Terminal in split window

### ISSUE THREAD

**Issue by vignesh0025** [caenrique/nvim-toggle-terminal#2]
Hi, 

Plugin works great as expected. It would be great if the same is available as a toggle split window apart from a separate buffer. 

Thanks.

**Comment by caenrique** [comment]
Hi, thanks for the suggestion :)
Unfortunately, it isn't the intention of this plugin to manage windows. I'd like to keep it simple.
However I believe that you can do that with a mapping and a simple function to keep track of the state of the split (open/closed)
